# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Hungary Radio Live' do
pod 'iOS-Slide-Menu', '1.4.4'
pod 'MarqueeLabel', '2.1.0'
pod 'StreamingKit', '0.1.25'
pod 'SCSiriWaveformView', '1.0.1'
pod 'ASOAnimatedButton', '1.0.1'
pod 'SVSegmentedControl@PTEz', '0.2.0.1'
pod 'ZGCountDownTimer', '2.0.1'
pod 'Google-AdMob-Ads-SDK', '6.12.2'
end

