# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Hungary Radio Live' do
pod 'iOS-Slide-Menu', '1.4.4'
pod 'MarqueeLabel', '2.1.0'
pod 'StreamingKit', '0.1.25'
pod 'SCSiriWaveformView', '1.0.1'
end

